export const inputFormElements = [
  {
    name: 'firstName',
    placeholder: 'Enter first name',
    label: 'First Name',
    variant: 'outlined',
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: 'lastName',
    placeholder: 'Enter last name',
    label: 'Last Name',
    variant: 'outlined',
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: 'username',
    placeholder: 'Enter Username',
    label: 'Username',
    variant: 'outlined',
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: 'password',
    type: 'password',
    placeholder: 'Enter Password',
    label: 'Password',
    variant: 'outlined',
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: 'roles',
    placeholder: 'Enter User role',
    label: 'Roles',
    variant: 'outlined',
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
];
